site_name: MySQL para Jornalistas

pages:
- Home: index.md
- Por quê isto importa?: por_que/isto_importa.md
- Tutoriais:
  - Introdução: tutoriais/introducao.md
  - Ferramentas: tutoriais/ferramentas.md
  - Um pouco sobre MySQL: tutoriais/mysql.md
- Entrevista com dados:
  - Baixe os dados que vamos usar: entrevista_com_dados/como_perguntar.md
  - CSV: entrevista_com_dados/csv.md
  - CSV para MySQL: entrevista_com_dados/csv-mysql.md
  - Como falar SQL: entrevista_com_dados/perguntas.md
- Resumo: resumo.md
- Sobre: sobre.md

theme: material

extra:
  palette:
    primary: 'teal'
    accent: 'grey'
